### ISSUE TITLE
yandex-cloud-dns.acme.cloud.yandex.com is forbidden

### ISSUE THREAD

**Issue by balagurrr** [yandex-cloud/cert-manager-webhook-yandex#4]
I didn't understand why the account doesn't have access
account has a role "dns.editor" in the directory

`cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="yandex-cloud-dns.acme.cloud.yandex.com is forbidden: User \"system:serviceaccount:cert-manager:certmanager-cert-manager\" cannot create resource \"yandex-cloud-dns\" in API group \"acme.cloud.yandex.com\" at the cluster scope" "key"="default/example-com-mzr2j-1730014154-645249238" `

please help in solving the problem

**Comment by Ditmarscehen** [comment]
It seems you have problems with Kubernetes Service Account. Have you changed [this RBAC rule](https://github.com/yandex-cloud/cert-manager-webhook-yandex/blob/master/deploy/cert-manager-webhook-yandex/templates/rbac.yaml#L101)?

**Comment by balagurrr** [comment]
you are right, the problem was in different default service accounts in certmanager (certmanager-certmanager) and webhook (cert-manager)
thanks a lot
