### ISSUE TITLE
Webhook does not work for kubernetes 1.26+

### ISSUE THREAD

**Issue by Pentusha** [yandex-cloud/cert-manager-webhook-yandex#9]
Hello, I'm trying to complete DNS-01 challenge on k3s version v1.28.5+k3s1

It looks like the webhook is not working correctly if you look at the logs:
```
pentusha at arco in ~ 
$ kubectl logs yandex-webhook-cert-manager-webhook-yandex-5cd9d96999-k49nf -n cert-manager --tail 2
E0206 11:33:52.928712       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PriorityLevelConfiguration: failed to list *v1beta1.PriorityLevelConfiguration: the server could not find the requested resource
E0206 11:34:15.513545       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.FlowSchema: failed to list *v1beta1.FlowSchema: the server could not find the requested resource
```
I did some googling and [found](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26) that this scheme was deprecated and was actually removed since 1.26.

**Comment by cyxou** [comment]
Should be reopened according to this: https://github.com/cert-manager/webhook-example/issues/27

**Comment by histme** [comment]
we have already tested new version on 1.28-1.30
